apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: t3.small
    # your K8 node can be anytime taken back by AWS
    spot: true
    desiredCapacity: 2
    # created to practice EBS static provisioning
    availabilityZones:
      - us-east-1
    ssh:
      publicKeyName: provisioners